import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/navbar/Navbar";
import Footer from "@/footer/Footer";
import ScrollReveal from "@/components/ScrollReveal";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <ScrollReveal />
        {children}
        <Footer />
      </body>
    </html>
  );
}
